// @flow
import {
    RUNNING,
    CYCLING_TRANSPORT,
    CYCLING_SPORT,
    MOUNTAIN_BIKINGS,
    SKATING,
    ROLLER_SKIING,
    SKIING_CROSS_COUNTRY,
    SKIING_DOWNHILL,
    SNOWBOARDING,
    KAYAKING,
    KITE_SURFING,
    ROWING,
    SAILING,
    WINDSURFING,
    FINTESS_WALKING,
    GOLFING,
    HIKING,
    ORIENTEERING,
    WALKING,
    RIDING,
    SWIMMING,
    CYCLING_INDOOR,
    OTHER,
    AEROBICS,
    BADMINTON,
    BASEBALL,
    BASKETBALL,
    BOXING,
    CLIMBING_STAIRS,
    CRICKET,
    ELLIPTICAL_TRAINING,
    DANCING,
    FENCING,
    FOOTBALL_AMERICAN,
    FOOTBALL_RUGBY,
    FOOTBALL_SOCCER,
    HANDBALL,
    HOCKEY,
    PILATES,
    POLO,
    SCUBA_DIVING,
    SQUASH,
    TABLE_TENIS,
    TENNIS,
    VOLEYBALL_BEACH,
    VOLEYBALL_INDOOR,
    WEIGHT_TRAINING,
    YOGA,
    MARTINAL_ARTS,
    GYMNASTICS,
    STEP_COUNTER,
    CIRKUIT_TRAINING,
    SKATEBOARDING,
    CLIMBING,
    KICK_SCOOTER,
    CANICROSS,
    FLOORBALL,
    ICE_SKATING,
    RUNNING_TREADMILL,
    SURFING,
    SNOWSHOEING,
    WHEELCHAIR,
    WALKING_TREADMILL,
    STAND_UP_PADDLING,
    TRAIL_RUNNING,
    ROWING_INDOORS,
    SKI_TOURING,
    ROPE_JUMPING,
    STRETCHING,
    PADDLE_TENNIS,
    PARAGLIDING,
} from './sports';

export default {
    [RUNNING]: 'Running',
    [CYCLING_TRANSPORT]: 'Cycling, transport',
    [CYCLING_SPORT]: 'Cycling, sport',
    [MOUNTAIN_BIKINGS]: 'Mountain biking',
    [SKATING]: 'Skating',
    [ROLLER_SKIING]: 'Roller skiing',
    [SKIING_CROSS_COUNTRY]: 'Skiing, cross country',
    [SKIING_DOWNHILL]: 'Skiing, downhill',
    [SNOWBOARDING]: 'Snowboarding',
    [KAYAKING]: 'Kayaking',
    [KITE_SURFING]: 'Kite surfing',
    [ROWING]: 'Rowing',
    [SAILING]: 'Sailing',
    [WINDSURFING]: 'Windsurfing',
    [FINTESS_WALKING]: 'Fitness walking',
    [GOLFING]: 'Golfing',
    [HIKING]: 'Hiking',
    [ORIENTEERING]: 'Orienteering',
    [WALKING]: 'Walking',
    [RIDING]: 'Riding',
    [SWIMMING]: 'Swimming',
    [CYCLING_INDOOR]: 'Cycling, Indoor',
    [OTHER]: 'Other',
    [AEROBICS]: 'Aerobics',
    [BADMINTON]: 'Badminton',
    [BASEBALL]: 'Baseball',
    [BASKETBALL]: 'Basketball',
    [BOXING]: 'Boxing',
    [CLIMBING_STAIRS]: 'Climbing stairs',
    [CRICKET]: 'Cricket',
    [ELLIPTICAL_TRAINING]: 'Elliptical training',
    [DANCING]: 'Dancing',
    [FENCING]: 'Fencing',
    [FOOTBALL_AMERICAN]: 'Football, American',
    [FOOTBALL_RUGBY]: 'Football, rugby',
    [FOOTBALL_SOCCER]: 'Football, soccer',
    [HANDBALL]: 'Handball',
    [HOCKEY]: 'Hockey',
    [PILATES]: 'Pilates',
    [POLO]: 'Polo',
    [SCUBA_DIVING]: 'Scuba diving',
    [SQUASH]: 'Squash',
    [TABLE_TENIS]: 'Table tennis',
    [TENNIS]: 'Tennis',
    [VOLEYBALL_BEACH]: 'Volleyball, beach',
    [VOLEYBALL_INDOOR]: 'Volleyball, indoor',
    [WEIGHT_TRAINING]: 'Weight training',
    [YOGA]: 'Yoga',
    [MARTINAL_ARTS]: 'Martial arts',
    [GYMNASTICS]: 'Gymnastics',
    [STEP_COUNTER]: 'Step counter',
    [CIRKUIT_TRAINING]: 'Circuit Training',
    [SKATEBOARDING]: 'Skateboarding',
    [CLIMBING]: 'Climbing',
    [KICK_SCOOTER]: 'Kick scooter',
    [CANICROSS]: 'Canicross',
    [FLOORBALL]: 'Floorball',
    [ICE_SKATING]: 'Ice skating',
    [RUNNING_TREADMILL]: 'Running (Treadmill)',
    [SURFING]: 'Surfing',
    [SNOWSHOEING]: 'Showshoeing',
    [WHEELCHAIR]: 'Wheelchair',
    [WALKING_TREADMILL]: 'Walking (Treadmill)',
    [STAND_UP_PADDLING]: 'Stand up paddling',
    [TRAIL_RUNNING]: 'Trail running',
    [ROWING_INDOORS]: 'Rowing (indoors)',
    [SKI_TOURING]: 'Ski touring',
    [ROPE_JUMPING]: 'Rope jumping',
    [STRETCHING]: 'Stretching',
    [PADDLE_TENNIS]: 'Paddle tennis',
    [PARAGLIDING]: 'Paragliding',
};
