import { Sport } from './sport';

export default {
    [Sport.RUNNING]: 'Running',
    [Sport.CYCLING_TRANSPORT]: 'Cycling, transport',
    [Sport.CYCLING_SPORT]: 'Cycling, sport',
    [Sport.MOUNTAIN_BIKINGS]: 'Mountain biking',
    [Sport.SKATING]: 'Skating',
    [Sport.ROLLER_SKIING]: 'Roller skiing',
    [Sport.SKIING_CROSS_COUNTRY]: 'Skiing, cross country',
    [Sport.SKIING_DOWNHILL]: 'Skiing, downhill',
    [Sport.SNOWBOARDING]: 'Snowboarding',
    [Sport.KAYAKING]: 'Kayaking',
    [Sport.KITE_SURFING]: 'Kite surfing',
    [Sport.ROWING]: 'Rowing',
    [Sport.SAILING]: 'Sailing',
    [Sport.WINDSURFING]: 'Windsurfing',
    [Sport.FINTESS_WALKING]: 'Fitness walking',
    [Sport.GOLFING]: 'Golfing',
    [Sport.HIKING]: 'Hiking',
    [Sport.ORIENTEERING]: 'Orienteering',
    [Sport.WALKING]: 'Walking',
    [Sport.RIDING]: 'Riding',
    [Sport.SWIMMING]: 'Swimming',
    [Sport.CYCLING_INDOOR]: 'Cycling, Indoor',
    [Sport.OTHER]: 'Other',
    [Sport.AEROBICS]: 'Aerobics',
    [Sport.BADMINTON]: 'Badminton',
    [Sport.BASEBALL]: 'Baseball',
    [Sport.BASKETBALL]: 'Basketball',
    [Sport.BOXING]: 'Boxing',
    [Sport.CLIMBING_STAIRS]: 'Climbing stairs',
    [Sport.CRICKET]: 'Cricket',
    [Sport.ELLIPTICAL_TRAINING]: 'Elliptical training',
    [Sport.DANCING]: 'Dancing',
    [Sport.FENCING]: 'Fencing',
    [Sport.FOOTBALL_AMERICAN]: 'Football, American',
    [Sport.FOOTBALL_RUGBY]: 'Football, rugby',
    [Sport.FOOTBALL_SOCCER]: 'Football, soccer',
    [Sport.HANDBALL]: 'Handball',
    [Sport.HOCKEY]: 'Hockey',
    [Sport.PILATES]: 'Pilates',
    [Sport.POLO]: 'Polo',
    [Sport.SCUBA_DIVING]: 'Scuba diving',
    [Sport.SQUASH]: 'Squash',
    [Sport.TABLE_TENIS]: 'Table tennis',
    [Sport.TENNIS]: 'Tennis',
    [Sport.VOLEYBALL_BEACH]: 'Volleyball, beach',
    [Sport.VOLEYBALL_INDOOR]: 'Volleyball, indoor',
    [Sport.WEIGHT_TRAINING]: 'Weight training',
    [Sport.YOGA]: 'Yoga',
    [Sport.MARTINAL_ARTS]: 'Martial arts',
    [Sport.GYMNASTICS]: 'Gymnastics',
    [Sport.STEP_COUNTER]: 'Step counter',
    [Sport.CIRKUIT_TRAINING]: 'Circuit Training',
    [Sport.SKATEBOARDING]: 'Skateboarding',
    [Sport.CLIMBING]: 'Climbing',
    [Sport.KICK_SCOOTER]: 'Kick scooter',
    [Sport.CANICROSS]: 'Canicross',
    [Sport.FLOORBALL]: 'Floorball',
    [Sport.ICE_SKATING]: 'Ice skating',
    [Sport.RUNNING_TREADMILL]: 'Running (Treadmill)',
    [Sport.SURFING]: 'Surfing',
    [Sport.SNOWSHOEING]: 'Showshoeing',
    [Sport.WHEELCHAIR]: 'Wheelchair',
    [Sport.WALKING_TREADMILL]: 'Walking (Treadmill)',
    [Sport.STAND_UP_PADDLING]: 'Stand up paddling',
    [Sport.TRAIL_RUNNING]: 'Trail running',
    [Sport.ROWING_INDOORS]: 'Rowing (indoors)',
    [Sport.SKI_TOURING]: 'Ski touring',
    [Sport.ROPE_JUMPING]: 'Rope jumping',
    [Sport.STRETCHING]: 'Stretching',
    [Sport.PADDLE_TENNIS]: 'Paddle tennis',
    [Sport.PARAGLIDING]: 'Paragliding',
};
