import { Sport } from '../Sport';
import { Point } from './Point';
import { Privacy } from '../Privacy';

export type Workout = {
    expand: string,
    id: number,
    sport: Sport,
    startTime: string,
    local_start_time: string,
    distance: number,
    duration: number,
    speed_avg: number,
    speed_max: number,
    altitude_min: number,
    altitude_max: number,
    ascent: number,
    descent: number,
    pb_count: number,
    calories: number,
    is_live: boolean,
    title?: string,
    message?: string,
    include_in_stats: boolean,
    can_fb_share_via_backend: boolean,
    author: {
        expand: string,
        id: number,
        first_name: string,
        last_name: string,
        picture: {
            url: string,
        },
        gender: number,
        is_premium: boolean,
        name: string,
        viewer_friendship: number,
    },
    is_peptalk_allowed: boolean,
    can_copy: boolean,
    weather: Object,
    heart_rate_avg: number,
    heart_rate_max: number,
    heart_rate_zones: Object,
    feed_id: number,
    laps: Object,
    small_encoded_polyline: string,
    records: Array<Object>,
    hashtags: Array<string>,
    tagged_users: Array<any>,
    pictures: Array<any>,
    points: {
        expand: string,
        id: number,
        points: Array<Point>,
    },
    show_map: Privacy,
    show_workout: Privacy,
    admin_rejected: boolean,
    personal_bests: Array<any>,
};
